### ISSUE TITLE
Why do you give up the project?

### ISSUE THREAD

**Issue by kingname** [Y-Vladimir/SmartDeblur#17]
I find the last update of this project is in 3 years ago, but why?

**Comment by hpchavaz** [comment]
may be : http://smartdeblur.net/buy.html

**Comment by rodrigopolo** [comment]
LOL

**Comment by programmin1** [comment]
Is this why the latest Github code says to upgrade to 2013 version?

**Comment by kingname** [comment]
Yes，it is.
